language: generic
sudo: required

before_install:
- sudo apt -qq update && sudo apt install -y latexmk texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-pictures texlive-science pgf
- gem install mdl
- pip install proselint

script:
- mkdir _build
- latexmk -pdf -outdir=_build rayterm-poster.tex
- mdl README.md
- proselint README.md

deploy:
  provider: releases
  api_key:
    secure: SOynY1hw+8dM1h6GAt/uUcH9mzE5VqWUhP72r+i91JTcsVuPFtmO4m1RIiP8Jyb3KHhEYqOspLIrk2fFTlwCpPx4O58ZV/FjEnG/BFZNNNuKipgORUES7w2E1zYh68LLcDnz34fFGqEuETwQhUxUrAs5lzI6wwo+dqg+E/s0Ea4ohY5l3aOLhVySsm1SmoV0/CRaAJMlzPRhLIBa0E9h4/fauT3iKRHM88TEPS/f9Q4RpeLV07ufA92pywwSNA3Ylsf2wORg2qtIDjd9BhflvmyHXjP6xBIYyKltcROJ9gpI8eWY7QZQPo+J5yJ/As5Q8Mf41KeL68DzUnkBr0lZMLXf0ruXSegUpBYBth7Ur729JinOU9oEGeqLxMqHWLPceavsgessG/rVvsehU8UXf1NIeHFP225ma8pYnPd83cJ3LH8RyqJnyInjPccyXwKu5AebUNiD3lg/ngIVBSx0Pt0kbtN/WzdotWKKMJ8jKgjnm5lSlwTAi44OFrMNop7TNeq6t+HNSao093jA3bsUlLtt8o+o9TffbQZTMrAzkv4CaKYrCQkTFrbojnmpsxDfwUu51DxUIhOtso3en3MD3wdLV5F5x9slD0Ef1Y9fXTqy6DGzpfThGgrSpQ3DQjAp7JbS9AkYxxy6AYysGUr7vDhz6x4IUg5b8jGzpkkVq8I=
  file: _build/rayterm-poster.pdf
  skip_cleanup: true
  on:
    tags: true
